version: 2.1

deploy:
docker:
  - image: circleci/openjdk:8-jdk-node
steps:
  - restore_cache:
      key: maven-{{ checksum "/tmp/maven_cache_seed" }}
  - run:
      name: AWS EC2 deploy
      command: |
        #upload all the code to machine
        scp -r -o StrictHostKeyChecking=no ./ ubuntu@18.217.87.1:/home/circleci-aws/
        #Run script inside of machine
        ssh -o StrictHostKeyChecking=no ubuntu@18.217.87.1 "./deploy.sh"
orbs:
  maven: circleci/maven@0.0.12

workflows:
  version: 2
  build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build

    
